<?xml version="1.0"?>
<package format="3">
  <name>wave_rover_control</name>
  <version>0.0.1</version>
  <description>Joystick to WAVE ROVER control with serial output</description>
  <maintainer email="you@example.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>nlohmann_json</depend>

  <exec_depend>python3</exec_depend>
</package>
